# Generated by Django 5.0.2 on 2024-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_ishturi_or_bolim_mahsulot_xato_bulim_xodim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinspection',
            name='ish_vaqti',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workinspection',
            name='izoh',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workinspection',
            name='xato_soni',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workinspection',
            name='yaroqli_product_soni',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
