# Generated by Django 5.0.2 on 2024-02-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_alter_workinspection_ish_vaqti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulim',
            name='bolim_rahbari',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
