# Generated by Django 5.0.2 on 2024-02-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0004_alter_bulim_bolim_rahbari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulim',
            name='bolim_rahbari',
        ),
    ]
