# Generated by Django 5.0.2 on 2024-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0006_bulim_bolim_rahbari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ishturi_or_Bolim',
            new_name='Ishturi',
        ),
    ]
